### ISSUE TITLE
Doesn't work with ES6 modules

### ISSUE THREAD

**Issue by time4nothing** [Luke265/discord-button-width#1]
Installed this package to try it (as discord is badly in need of equal sized buttons), but it will not import the modules. I receive the below error:

```
import { getStringWidth, padStringToWidth } from 'discord-button-width';
         ^^^^^^^^^^^^^^
SyntaxError: Named export 'getStringWidth' not found. The requested module 'discord-button-width' is a CommonJS module, which may not support all module.exports as named exports.
```

I do not want to use CommonJS, so hopefully I'm just doing something wrong, and your code does support ES6 modules :)

Using discord.js v14 code, in case that matters.

**Comment by Luke265** [comment]
This should be fixed in v1.1.1
